apiVersion: roundtable.lsst.codes/v1beta1
kind: StrimziSchemaRegistry
metadata:
  name: confluent-schema-registry
  labels:
    strimzi.io/cluster: test-cluster
spec:
  strimziVersion: v1
  listener: tls
  registryImageTag: "8.0.3"
  serviceType: NodePort
